version: '3.7'

networks:
  kafka-net:
    driver: bridge

services:

  hive:
    build: 
      context: .
      dockerfile: Hive/Dockerfile_hive
    container_name: hive
    ports:
      - "10000:10000"  # HiveServer2
      - "10002:10002"  # Hive Metastore
    environment:
      SERVICE_NAME: hiveserver2
    volumes:
      - ../data:/app/data
    networks:
      - kafka-net

  superset:
    build:
      context: .
      dockerfile: Superset/Dockerfile_superset
    container_name: superset
    ports:
      - "8088:8088"
    volumes:
      - ../data:/app/data
      - ./superset/superset_config.py:/app/pythonpath/superset_config.py
    networks:
      - kafka-net
    depends_on: [hive]
    environment:
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin







